### ISSUE TITLE
Invalid client secret is provided

### ISSUE THREAD

**Issue by Bigben83** [CoasterKaty/PHPAzureADoAuth#1]
Great Simple Little Script Katy, Well Done

Just one question I have set this up and created the following 
Directory (tenant) ID:
Application (client) ID:
Client secrets:

When you go to sign in it get so far then gives this error
`AADSTS7000215: Invalid client secret is provided. Trace ID: XXXXXXXXX Correlation ID: XXXXXXXXX  Timestamp: 2021-08-31 05:18:23Z`

Is there something that I am doing wrong ?

**Comment by CoasterKaty** [comment]
Are you putting the secret ID or the secret value into the script? Needs to be the value/password, not the GUID ID.

**Comment by Bigben83** [comment]
Oh thanks yes that was the issue. didnt even pick that up. Thanks heaps.

**Comment by Bigben83** [comment]
Is there any way of getting the user photo and address details in the return data ?

**Comment by CoasterKaty** [comment]
You’ll probably need to get those from Graph using the oauth token you’ve already obtained. If I get time tomorrow I’ll see about adding an example into the project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CoasterKaty** [comment]
I've done a few updates which will pull the user's photo and whatever their basic directory profile contains. Changes in most of the files to support this, as we need to save the access token in order to authenticate against Graph API.

**Comment by Bigben83** [comment]
Absolutely perfect. worked like a charm, I made some changes to the Image return just so I could format it in bootstrap nav header etc.
One thing I have noticed is that sometimes on login it reverts to office.com instead of the redirect url.
