### ISSUE TITLE
$this->Token

### ISSUE THREAD

**Issue by mischapeters** [CoasterKaty/PHPAzureADoAuth#17]
What does this variable do?

` $this->Token = $res['txtToken'];`

https://github.com/CoasterKaty/PHPAzureADoAuth/blob/2e004589f138f83da3c237e31b4aa6ad0e50bc01/inc/auth.php#L77C26-L77C27

**Comment by CoasterKaty** [comment]
It holds the access token which is required when making further requests to graph eg in inc/graph.php in the auth bearer header

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mischa Peters ***@***.***>
Sent: Saturday, July 8, 2023 2:49:44 PM
To: CoasterKaty/PHPAzureADoAuth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CoasterKaty/PHPAzureADoAuth] $this->Token (Issue #17)


What does this variable do?

$this->Token = $res['txtToken'];

https://github.com/CoasterKaty/PHPAzureADoAuth/blob/2e004589f138f83da3c237e31b4aa6ad0e50bc01/inc/auth.php#L77C26-L77C27

**Comment by mischapeters** [comment]
Thank you!
That's why I couldn't find anything else referencing it. I removed all the graph stuff. :)
