### ISSUE TITLE
response from oAuth server is Base64URL, but is decoded using base64_decode in www/oauth.php

### ISSUE THREAD

**Issue by Jakob-Go** [CoasterKaty/PHPAzureADoAuth#20]
The token fields in the .json response from the server are encoded using base64URL, which is different from regular base64.
This usually works fine; however, this means the response can include the characters '\_' and '-', neither of which are valid base64 characters. This throws errors if the id_token-field contains either of these characters. They replace the base64-characters '/' (replacing '\_' ) and '+' (replacing '-' respectively, though. This can be fixed using
```
$idToken = base64_decode(str_replace("_", "/", str_replace("-", "+", explode('.', $reply->id_token)[1])));
```
instead.

**Comment by boiss** [comment]
This should be added to the repo as some users might not be able to login and create a broken token response.
