### ISSUE TITLE
Session_start() & Cannot modify header information errors 

### ISSUE THREAD

**Issue by mwj8890** [CoasterKaty/PHPAzureADoAuth#5]
I am getting the following errors when browsing to the website. 

PHP Warning: session_start(): Cannot start session when headers already sent in /var/www/co.uk/cover/inc/auth.php on line 30
PHP Warning: Cannot modify header information – headers already sent by (output started at /var/www/co.uk/cover/inc/auth.php:155) in /var/www/co.uk/cover/inc/auth.php on line 97

I have check the config.inc file and there are no blank lines outside the php tags as suggested. 

![error](https://user-images.githubusercontent.com/56802412/144404530-8c234d4b-421f-4da9-9710-1f32e5e257d0.PNG)

**Comment by CoasterKaty** [comment]
The version of inc/auth.php in the repo is 154 lines long - you've got a message pointing to line 155 so make sure there isn't any whitespace at the end of auth.php too.

**Comment by mwj8890** [comment]
Thanks Katy. That was the issue.
